project:
  type: website
  output-dir: docs

website:
    title: "Alex Bradley Newhouse"
    navbar:
        background: primary
        search: true
        left:
            - text: "CV"
              href: cv.html
            - text: "Dissertation"
              href: dissertation.html
            - text: "Research"
              href: research.html
            - text: "Teaching" 
              href: teaching.html

format:
  html:
    theme: lumen
    css: styles.css
    toc: true

editor: visual